// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/proto-files/domain/writtenContent.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contenttype int32

const (
	Contenttype_POST     Contenttype = 0
	Contenttype_ARTICLE  Contenttype = 1
	Contenttype_REACTION Contenttype = 2
	Contenttype_TWEET    Contenttype = 3
	Contenttype_BLOG     Contenttype = 4
)

// Enum value maps for Contenttype.
var (
	Contenttype_name = map[int32]string{
		0: "POST",
		1: "ARTICLE",
		2: "REACTION",
		3: "TWEET",
		4: "BLOG",
	}
	Contenttype_value = map[string]int32{
		"POST":     0,
		"ARTICLE":  1,
		"REACTION": 2,
		"TWEET":    3,
		"BLOG":     4,
	}
)

func (x Contenttype) Enum() *Contenttype {
	p := new(Contenttype)
	*p = x
	return p
}

func (x Contenttype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Contenttype) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_files_domain_writtenContent_proto_enumTypes[0].Descriptor()
}

func (Contenttype) Type() protoreflect.EnumType {
	return &file_internal_proto_files_domain_writtenContent_proto_enumTypes[0]
}

func (x Contenttype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Contenttype.Descriptor instead.
func (Contenttype) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_files_domain_writtenContent_proto_rawDescGZIP(), []int{0}
}

// Supporting definitions
type Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Author) Reset() {
	*x = Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_files_domain_writtenContent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_files_domain_writtenContent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_internal_proto_files_domain_writtenContent_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Provide your message definitions for the core elements of your domain here
type Article struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle string      `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Content  string      `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Author   *Author     `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Type     Contenttype `protobuf:"varint,6,opt,name=type,proto3,enum=domain.Contenttype" json:"type,omitempty"`
}

func (x *Article) Reset() {
	*x = Article{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_files_domain_writtenContent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_files_domain_writtenContent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_internal_proto_files_domain_writtenContent_proto_rawDescGZIP(), []int{1}
}

func (x *Article) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Article) GetType() Contenttype {
	if x != nil {
		return x.Type
	}
	return Contenttype_POST
}

var File_internal_proto_files_domain_writtenContent_proto protoreflect.FileDescriptor

var file_internal_proto_files_domain_writtenContent_proto_rawDesc = []byte{
	0x0a, 0x30, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x77, 0x72,
	0x69, 0x74, 0x74, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x18, 0x0a, 0x06, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xb6, 0x01, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x74, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x47, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x74, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x50, 0x4f, 0x53, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x52, 0x54, 0x49, 0x43, 0x4c,
	0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x57, 0x45, 0x45, 0x54, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04,
	0x42, 0x4c, 0x4f, 0x47, 0x10, 0x04, 0x42, 0x16, 0x5a, 0x14, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_files_domain_writtenContent_proto_rawDescOnce sync.Once
	file_internal_proto_files_domain_writtenContent_proto_rawDescData = file_internal_proto_files_domain_writtenContent_proto_rawDesc
)

func file_internal_proto_files_domain_writtenContent_proto_rawDescGZIP() []byte {
	file_internal_proto_files_domain_writtenContent_proto_rawDescOnce.Do(func() {
		file_internal_proto_files_domain_writtenContent_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_files_domain_writtenContent_proto_rawDescData)
	})
	return file_internal_proto_files_domain_writtenContent_proto_rawDescData
}

var file_internal_proto_files_domain_writtenContent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_files_domain_writtenContent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_files_domain_writtenContent_proto_goTypes = []interface{}{
	(Contenttype)(0), // 0: domain.Contenttype
	(*Author)(nil),   // 1: domain.Author
	(*Article)(nil),  // 2: domain.Article
}
var file_internal_proto_files_domain_writtenContent_proto_depIdxs = []int32{
	1, // 0: domain.Article.author:type_name -> domain.Author
	0, // 1: domain.Article.type:type_name -> domain.Contenttype
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_files_domain_writtenContent_proto_init() }
func file_internal_proto_files_domain_writtenContent_proto_init() {
	if File_internal_proto_files_domain_writtenContent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_files_domain_writtenContent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_files_domain_writtenContent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Article); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_files_domain_writtenContent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_files_domain_writtenContent_proto_goTypes,
		DependencyIndexes: file_internal_proto_files_domain_writtenContent_proto_depIdxs,
		EnumInfos:         file_internal_proto_files_domain_writtenContent_proto_enumTypes,
		MessageInfos:      file_internal_proto_files_domain_writtenContent_proto_msgTypes,
	}.Build()
	File_internal_proto_files_domain_writtenContent_proto = out.File
	file_internal_proto_files_domain_writtenContent_proto_rawDesc = nil
	file_internal_proto_files_domain_writtenContent_proto_goTypes = nil
	file_internal_proto_files_domain_writtenContent_proto_depIdxs = nil
}
