// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/proto-files/domain/spokenContent.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	domain "internal/gRPC/domain"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Content categories
type AudioRecording struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string              `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Link  *domain.ContentLink `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *AudioRecording) Reset() {
	*x = AudioRecording{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_files_domain_spokenContent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioRecording) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRecording) ProtoMessage() {}

func (x *AudioRecording) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_files_domain_spokenContent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRecording.ProtoReflect.Descriptor instead.
func (*AudioRecording) Descriptor() ([]byte, []int) {
	return file_internal_proto_files_domain_spokenContent_proto_rawDescGZIP(), []int{0}
}

func (x *AudioRecording) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioRecording) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AudioRecording) GetLink() *domain.ContentLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type Interview struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId uint32 `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	GuestId  uint32 `protobuf:"varint,3,opt,name=guest_id,json=guestId,proto3" json:"guest_id,omitempty"`
	Topic    string `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Title    string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Interview) Reset() {
	*x = Interview{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_files_domain_spokenContent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interview) ProtoMessage() {}

func (x *Interview) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_files_domain_spokenContent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interview.ProtoReflect.Descriptor instead.
func (*Interview) Descriptor() ([]byte, []int) {
	return file_internal_proto_files_domain_spokenContent_proto_rawDescGZIP(), []int{1}
}

func (x *Interview) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Interview) GetAuthorId() uint32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Interview) GetGuestId() uint32 {
	if x != nil {
		return x.GuestId
	}
	return 0
}

func (x *Interview) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Interview) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_internal_proto_files_domain_spokenContent_proto protoreflect.FileDescriptor

var file_internal_proto_files_domain_spokenContent_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x70,
	0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x0e, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x7f, 0x0a, 0x09, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_files_domain_spokenContent_proto_rawDescOnce sync.Once
	file_internal_proto_files_domain_spokenContent_proto_rawDescData = file_internal_proto_files_domain_spokenContent_proto_rawDesc
)

func file_internal_proto_files_domain_spokenContent_proto_rawDescGZIP() []byte {
	file_internal_proto_files_domain_spokenContent_proto_rawDescOnce.Do(func() {
		file_internal_proto_files_domain_spokenContent_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_files_domain_spokenContent_proto_rawDescData)
	})
	return file_internal_proto_files_domain_spokenContent_proto_rawDescData
}

var file_internal_proto_files_domain_spokenContent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_files_domain_spokenContent_proto_goTypes = []interface{}{
	(*AudioRecording)(nil),     // 0: domain.AudioRecording
	(*Interview)(nil),          // 1: domain.Interview
	(*domain.ContentLink)(nil), // 2: domain.ContentLink
}
var file_internal_proto_files_domain_spokenContent_proto_depIdxs = []int32{
	2, // 0: domain.AudioRecording.link:type_name -> domain.ContentLink
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_files_domain_spokenContent_proto_init() }
func file_internal_proto_files_domain_spokenContent_proto_init() {
	if File_internal_proto_files_domain_spokenContent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_files_domain_spokenContent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioRecording); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_files_domain_spokenContent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interview); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_files_domain_spokenContent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_files_domain_spokenContent_proto_goTypes,
		DependencyIndexes: file_internal_proto_files_domain_spokenContent_proto_depIdxs,
		MessageInfos:      file_internal_proto_files_domain_spokenContent_proto_msgTypes,
	}.Build()
	File_internal_proto_files_domain_spokenContent_proto = out.File
	file_internal_proto_files_domain_spokenContent_proto_rawDesc = nil
	file_internal_proto_files_domain_spokenContent_proto_goTypes = nil
	file_internal_proto_files_domain_spokenContent_proto_depIdxs = nil
}
